[package]
name = "central_limit_thm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.39"
plotters = "0.3.5"
rand = "0.8"
rayon = "1.8.0"
